stages:
  - lint
  - test

lint:
  stage: lint
  image: python:3.12  # Используем образ Python 3.12
  script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install pre-commit
    - pre-commit run --all-files
  only:
    - main
    - develop

test:
  stage: test
  image: docker:latest  # Используем образ Docker
  services:
    - docker:dind

  variables:
    DOCKER_DRIVER: overlay2

  before_script:
    - docker info
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - docker-compose up -d

  script:
    - pytest

  after_script:
    - docker-compose down

  only:
    - main
    - develop
