services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/tweet-clone
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: db_container
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tweet-clone
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d  # монтирование conf.d
      - ./dist:/app/dist
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata:
