name: CI

on:
  push:
    branches:
      - main  # Основная ветка продакшн
      - develop  # Ветка разработки (тест)
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Code Quality Checks  # Название задания
    runs-on: ubuntu-latest  # Среда выполнения задания

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # Описание: Этот шаг клонирует ваш репозиторий на машину GitHub Actions.

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Убедитесь, что ваш проект совместим с этой версией Python
        # Описание: Этот шаг устанавливает версию Python, указанную в конфигурации.

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 isort black mypy
        # Описание: Этот шаг обновляет pip и устанавливает необходимые зависимости для проекта из файла requirements.txt.

      - name: Lint code with Flake8
        run: flake8 .
        # Описание: Этот шаг проверяет ваш код с помощью Flake8.

      - name: Check import sorting with isort
        run: isort .
        # Описание: Этот шаг проверяет сортировку импортов с помощью isort.

      - name: Check code formatting with Black
        run: black .
        # Описание: Этот шаг проверяет форматирование кода с помощью Black.

      - name: Static type analysis with Mypy
        run: mypy .
        # Описание: Этот шаг выполняет статический анализ типов с помощью Mypy.

  test:
    name: Run Tests  # Название задания
    runs-on: ubuntu-latest  # Среда выполнения задания

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # Описание: Этот шаг клонирует ваш репозиторий на машину GitHub Actions.

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Убедитесь, что ваш проект совместим с этой версией Python
        # Описание: Этот шаг устанавливает версию Python, указанную в конфигурации.

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        # Описание: Этот шаг обновляет pip и устанавливает зависимости из файла requirements.txt.

      - name: Run tests with pytest
        run: pytest
        # Описание: Этот шаг запускает тесты с использованием pytest.
